### ISSUE TITLE
Change "installation" text

### ISSUE THREAD

**Issue by Dalmirog** [anabellaspinelli/OctoPosh#5]
**Current**: Click ***here*** for installation instructions using GitHub.
**Expected**: Click  ***here*** for alternative installation methods

**Comment by anabellaspinelli** [comment]
https://github.com/Dalmirog/OctoPosh/wiki/Installing-the-module
<https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FDalmirog%2FOctoPosh%2Fwiki%2FInstalling-the-module&sa=D&sntz=1&usg=AFQjCNE1MOjnDFcP9EMFyboPzibQt7NO6g>

**Comment by anabellaspinelli** [comment]
Done :octocat:
